---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-letsencrypt-dns-cloudflare
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "__{{infra-emails:f:hh}}__"
    privateKeySecretRef:
      name: cluster-letsencrypt-dns-cloudflare
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
