apiVersion: v1
kind: ServiceAccount
metadata:
  name: restart
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restart-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restart-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: restart
roleRef:
  kind: Role
  name: restart-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: restart
  namespace: default
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: restart
          volumes:
            - name: temp
              emptyDir:
                sizeLimit: 50Mi
          containers:
            - name: app
              image: cloudpublic/default/restart:latest
              imagePullPolicy: Always
              env:
                - name: STATE_FILE
                  value: "/tmp/restart/operator_state.json"
              volumeMounts:
                - name: temp
                  mountPath: /tmp/restart
          restartPolicy: OnFailure
