---
apiVersion: v1
kind: Secret
metadata:
  name: aws-s3-upload
  namespace: longhorn-system
stringData:
  AWS_ACCESS_KEY_ID: "__{{longhorn.secret.aws-s3-upload:f:keyid}}__"
  AWS_SECRET_ACCESS_KEY: "__{{longhorn.secret.aws-s3-upload:f:accesskey}}__"

---
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-crypto
  namespace: longhorn-system
stringData:
  CRYPTO_KEY_VALUE: "__{{longhorn.secret.longhorn-crypto.key}}__"
  CRYPTO_KEY_PROVIDER: "secret"
  CRYPTO_KEY_CIPHER: "aes-xts-plain64"
  CRYPTO_KEY_HASH: "sha256"
  CRYPTO_KEY_SIZE: "256"
  CRYPTO_PBKDF: "argon2i"

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-crypto-global
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  encrypted: "true"
  # global secret that contains the encryption key that will be used for all volumes
  csi.storage.k8s.io/provisioner-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/provisioner-secret-namespace: "longhorn-system"
  csi.storage.k8s.io/node-publish-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/node-publish-secret-namespace: "longhorn-system"
  csi.storage.k8s.io/node-stage-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/node-stage-secret-namespace: "longhorn-system"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: default-common-encrypted
  namespace: default
spec:
  storageClassName: longhorn-crypto-global
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
