---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: longhorn-datamanager
  namespace: chameleon
  labels:
    app: longhorn-datamanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: longhorn-datamanager
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: "100%"
  template:
    metadata:
      labels:
        app: longhorn-datamanager
    spec:
      terminationGracePeriodSeconds: 3
      nodeSelector:
        kubernetes.io/hostname: nur
      volumes:
        - name: longhorn
          persistentVolumeClaim:
            claimName: data
        - name: local
          hostPath:
            path: /mnt/runtime-data-app/chameleon
            type: Directory
      containers:
        - name: app
          image: ubuntu:22.04
          imagePullPolicy: Always
          command: ["sleep", "infinity"]
          workingDir: /data
          volumeMounts:
            - name: longhorn
              mountPath: /data/longhorn
            - name: local
              mountPath: /data/local
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
