---
version: "3"
services:
  nginx:
    image: __{{umbilical.deploy.cloudpublic_registry_host}}__/umbilical/nginx:latest
    environment:
      TZ: "__{{umbilical.deploy.timezone}}__"
    volumes:
      - /var/log/umbilical/nginx:/var/log/nginx
      - ../../static/letsencrypt:/etc/letsencrypt
      - ./nginx/configs/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/configs/robots.conf:/etc/nginx/robots.conf
    ports:
      - 25443:443
    restart: unless-stopped

  wireguard:
    image: __{{umbilical.deploy.cloudpublic_registry_host}}__/umbilical/wireguard:latest
    environment:
      TZ: "__{{umbilical.deploy.timezone}}__"
      WG_HOST: "wireguard.__{{infra.domains:f:u}}__"
      PASSWORD_HASH: "__{{umbilical.wireguard:f:hash}}__"
      PORT: "51821"
      WG_PORT: "51820"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    volumes:
      - /root/wireguard:/etc/wireguard
    ports:
      - 51820:51820/udp
    restart: unless-stopped
